"""
test_generator.py — Auto-generate pytest regression tests from fuzzer results.

After KAVACH-AIDR finds a vulnerability and generates a patch,
this module creates a pytest test suite that:
  1. Proves the exploit WORKED before the patch (expected to fail on old code)
  2. Proves the exploit FAILS after the patch (the regression test)
  3. Proves normal functionality still works (no broken behavior)

These tests serve as the "regression test harness" — they lock in
the fix so the vulnerability can never silently creep back.
"""

import ast
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from kavach.fuzzer.mutation_engine import Payload
from kavach.fuzzer.crash_triager import CrashReport


@dataclass
class GeneratedTestSuite:
    """A generated pytest test module."""
    test_code    : str
    test_count   : int
    filepath     : Path
    function_name: str
    vuln_type    : str


def generate_tests(
    function_name     : str,
    vuln_type         : str,
    source_filepath   : str,
    exploitable_inputs: list[Payload],
    safe_inputs       : list[tuple[str, str]],   # (input, expected_normal_output_type)
    crashes           : list[CrashReport],
    output_dir        : str = "tests/generated",
) -> GeneratedTestSuite:
    """
    Generate a complete pytest test file for a patched vulnerability.

    Args:
        function_name      : Name of the patched function
        vuln_type          : e.g. "SQL_INJECTION"
        source_filepath    : Path to the source file (imported in tests)
        exploitable_inputs : Payloads that triggered the bug (now must NOT crash)
        safe_inputs        : (input, expected_type) pairs for normal behavior
        crashes            : Crash reports from pre-patch fuzzing
        output_dir         : Where to write the test file

    Returns:
        GeneratedTestSuite with the generated pytest code.
    """
    module_name = Path(source_filepath).stem
    test_name   = f"test_regression_{module_name}_{function_name}_{vuln_type.lower()}"

    lines = [
        '"""',
        f'Regression tests for {vuln_type} in {function_name}().',
        '',
        f'Auto-generated by KAVACH-AIDR — Indian Armed Forces Cyber Reasoner.',
        f'Source: {source_filepath}',
        '',
        'These tests MUST PASS after the patch is applied.',
        'If they fail, the patch is incomplete or was reverted.',
        '"""',
        '',
        'import pytest',
        'import sys',
        f'import importlib.util',
        '',
        '',
        '# ── Load the target module ───────────────────────────────────────────────',
        f'def _load_module():',
        f'    spec = importlib.util.spec_from_file_location(',
        f'        "{module_name}",',
        f'        r"{source_filepath}",',
        f'    )',
        f'    module = importlib.util.module_from_spec(spec)',
        f'    spec.loader.exec_module(module)',
        f'    return module',
        '',
        f'MODULE = _load_module()',
        f'TARGET_FUNC = getattr(MODULE, "{function_name}")',
        '',
        '',
    ]

    test_count = 0

    # ── Section 1: Exploit inputs should NOT crash the patched function ───
    lines += [
        '# ==============================================================================',
        f'# Section 1: Exploit Inputs — must NOT trigger {vuln_type} after patch',
        '# ==============================================================================',
        '',
    ]

    for i, payload in enumerate(exploitable_inputs[:10]):
        safe_val = repr(payload.value[:200])
        desc     = payload.description.replace("'", "\\'")[:60]
        lines += [
            f'def test_exploit_{i+1}_does_not_crash():',
            f'    """',
            f'    [{vuln_type}] Input: {desc}',
            f'    This payload triggered the bug BEFORE patching.',
            f'    After patch, it must NOT cause a security-relevant exception.',
            f'    """',
            f'    try:',
            f'        TARGET_FUNC({safe_val})',
            f'    except Exception as e:',
            f'        exc_type = type(e).__name__',
            f'        # Security-relevant exceptions must NOT occur',
            f'        assert exc_type not in (',
            f'            "sqlite3.OperationalError", "PermissionError",',
            f'            "OSError", "pickle.UnpicklingError",',
            f'        ), f"Patch failed: {{exc_type}} still triggered by exploit input"',
            f'',
        ]
        test_count += 1

    # ── Section 2: Normal inputs should still work ─────────────────────────
    lines += [
        '',
        '# ==============================================================================',
        '# Section 2: Normal Inputs — functional regression (no broken behavior)',
        '# ==============================================================================',
        '',
    ]

    normal_inputs = _generate_normal_inputs(vuln_type)
    for i, (inp, description) in enumerate(normal_inputs[:5]):
        safe_inp = repr(inp[:100])
        lines += [
            f'def test_normal_input_{i+1}_accepted():',
            f'    """Normal input: {description}"""',
            f'    # Should not raise unexpected exceptions',
            f'    try:',
            f'        result = TARGET_FUNC({safe_inp})',
            f'    except Exception as e:',
            f'        exc_type = type(e).__name__',
            f'        # Only allow expected/handled exceptions',
            f'        assert exc_type in ("ValueError", "TypeError", "FileNotFoundError"), \\',
            f'               f"Unexpected exception on normal input: {{exc_type}}: {{e}}"',
            f'',
        ]
        test_count += 1

    # ── Section 3: Boundary inputs ─────────────────────────────────────────
    lines += [
        '',
        '# ==============================================================================',
        '# Section 3: Boundary / Edge Cases',
        '# ==============================================================================',
        '',
    ]

    boundary_tests = [
        ('""',              "Empty string"),
        ('" "',             "Single space"),
        ('"a" * 1000',      "Long string"),
        ('"\\x00"',         "Null byte"),
    ]
    for i, (inp_expr, desc) in enumerate(boundary_tests):
        lines += [
            f'def test_boundary_{i+1}_{desc.lower().replace(" ", "_")}():',
            f'    """Boundary: {desc} — must not crash with unhandled exception."""',
            f'    try:',
            f'        TARGET_FUNC({inp_expr})',
            f'    except (ValueError, TypeError):',
            f'        pass  # Expected — not a security issue',
            f'    except Exception as e:',
            f'        pytest.fail(f"Unhandled exception on boundary input: {{type(e).__name__}}: {{e}}")',
            f'',
        ]
        test_count += 1

    # ── Section 4: Parameterized exploit test ─────────────────────────────
    if exploitable_inputs:
        payloads_repr = repr([p.value[:100] for p in exploitable_inputs[:5]])
        lines += [
            '',
            '# ==============================================================================',
            '# Section 4: Parameterized — all exploit inputs in one test',
            '# ==============================================================================',
            '',
            f'@pytest.mark.parametrize("payload", {payloads_repr})',
            f'def test_no_injection_with_exploit_payloads(payload):',
            f'    """All original exploit payloads must be neutralized by the patch."""',
            f'    try:',
            f'        TARGET_FUNC(payload)',
            f'    except Exception as e:',
            f'        ALLOWED = ("ValueError", "TypeError", "AttributeError")',
            f'        assert type(e).__name__ in ALLOWED, \\',
            f'               f"Security exception still possible: {{type(e).__name__}}: {{e}}"',
            f'',
        ]
        test_count += 1

    # ── Write file ────────────────────────────────────────────────────────
    test_code = "\n".join(lines)
    output_path = Path(output_dir) / f"{test_name}.py"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(test_code, encoding="utf-8")

    return GeneratedTestSuite(
        test_code     = test_code,
        test_count    = test_count,
        filepath      = output_path,
        function_name = function_name,
        vuln_type     = vuln_type,
    )


def _generate_normal_inputs(vuln_type: str) -> list[tuple[str, str]]:
    """Generate safe/normal inputs appropriate for the vulnerability type."""
    return {
        "SQL_INJECTION": [
            ("alice", "Normal username"),
            ("john_doe", "Underscore username"),
            ("user123", "Alphanumeric"),
            ("admin", "Admin username (should fail auth, not crash)"),
            ("test user", "Username with space"),
        ],
        "PATH_TRAVERSAL": [
            ("report.txt", "Normal filename"),
            ("subdir/file.txt", "Subdirectory file"),
            ("2024_report.pdf", "Date-prefixed filename"),
        ],
        "COMMAND_INJECTION": [
            ("192.168.1.1", "Valid IP"),
            ("localhost", "Hostname"),
            ("google.com", "Domain name"),
        ],
        "DESERIALIZATION": [
            ('{"key": "value"}', "Valid JSON"),
            ("hello", "Simple string"),
        ],
        "HARDCODED_SECRET": [
            ("testpassword", "Test password"),
            ("hunter2", "Common test password"),
        ],
    }.get(vuln_type, [("test_input", "Generic test"), ("hello world", "Simple input")])
